# Generated by Django 4.2.4 on 2023-08-24 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_rename_title_authentication_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="authentication",
            name="invite",
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
