# Generated by Django 4.2.4 on 2024-04-23 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0003_authentication_invite"),
    ]

    operations = [
        migrations.AddField(
            model_name="authentication",
            name="invite_activated",
            field=models.BooleanField(default=False, verbose_name="Активирован код"),
        ),
    ]
